language: generic
sudo: required
services:
    - docker
    
before_install:
    - docker build -t tsetsongdevops/docker-react -f Dockerfile.dev .

script:
    - docker run -e CI=true tsetsongdevops/docker-react npm run test

deploy:
    provider: elasticbeanstalk
    region : "ap-southeast-1"
    app: "docker-react"
    env: "Dockerreact-env"
    bucket_name: "elasticbeanstalk-ap-southeast-1-708339594433"
    bucket_path: "docket-react"
    on:
        branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: "$AWS_SECRET_KEY"
        